stages:
  - build

build:
  stage: build
  image: node
  before_script:
    - apt-get update
    - apt-get install -y graphicsmagick
    - npm install --save-dev grunt-cli
    - npm install
  only:
    - master
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour
